### ISSUE TITLE
Sample code in readme.md mentions v1.1, but latest release is 1.0

### ISSUE THREAD

**Issue by mherbrich** [szenius/set-timezone#2]
Hi,
was a little bit confusing for me:
In the readme.md sample code for usage is `uses: actions/set-timezone-action@v1.1`, but the latest release is v1.0. So the sample code doesn't work.
Should be fixed.

**Comment by carlosal1015** [comment]
In the case of linux, it could be better:

```yml
jobs:
  buid_iso:
    runs-on: ubuntu-20.04
    steps:
      - name: Display date with respect to timezone
        run: |
          ln -sf /usr/share/zoneinfo/Asia/Singapore /etc/localtime
          date
```
**Reference:** [How to Set or Change the Time Zone in Linux](https://linuxize.com/post/how-to-set-or-change-timezone-in-linux)
