### ISSUE TITLE
Does this work with schedule: cron ?

### ISSUE THREAD

**Issue by Tao-Galasse** [szenius/set-timezone#6]
Hello !

I'm trying to set up a github action to run at a given hour.

I'm not very familiar with all of this; does this action can allow me to set up a cron at a specific timezone ? I would like to do something like this:

```yml
on:
  schedule:
    - cron: '0 8 * * 1,2,3,4,5' # Monday through Friday at 8AM

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set timezone to Europe/Paris
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Paris"
    - name: Do my stuff
      run: echo 'foobar'
```
